### ISSUE TITLE
tabId undefined in background.js:29

### ISSUE THREAD

**Issue by rheum** [Maluen/Backbone-Debugger#51]
I'm doing research on how to automatically detect possible race conditions in chrome extensions and spent some time reviewing your background.js. By coincidence I got stuck on [line 29 of background.js](https://github.com/Maluen/Backbone-Debugger/blob/master/js/background.js#L29). I believe tabId is undefined at this position which might cause trouble? Or possibly I'm just missing something.

**Comment by Maluen** [comment]
It isn't undefined because we assume that the first message we get we'll always be "identification", and we execute `tabId = message.data` when this happens.
Since tabId is defined in the outer scope, it will then be accessible when handling any subsequent message.

Basically tabs register themselves by sending their IDs that we then use as port IDs.

**Comment by rheum** [comment]
Ah, thank you for the explaination. I was mislead by the `var tabId` declaration, which I assumed declared the variable in the temporary local scope of the function.
